packages:
  - 'packages/sdk'
  - 'packages/adapters/*'
  - 'packages/appkit'
  - 'packages/common'
  - 'packages/ui'
  - 'packages/core'
  - 'packages/appkit-utils'
  - 'packages/scaffold-ui'
  - 'packages/polyfills'
  - 'packages/wallet'
  - 'packages/siwe'
  - 'packages/siwx'
  - 'packages/wallet-button'
  - 'packages/cdn'
  - 'packages/experimental'
  - 'packages/cli'
  - 'examples/*'
  - 'packages/ui-new'
  - '!packages/appkit-new'