name: Publish to NPM
on:
  push:
    branches:
      - main
      - feature/*package*
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@to-nexus"
          always-auth: true
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - name: Configure NPM Auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@to-nexus:registry=https://npm.pkg.github.com" >> .npmrc
          echo "registry=https://npm.pkg.github.com" >> .npmrc
      - name: Update pnpm-lock.yaml
        run: |
          sed -i 's/@cross\/sdk/@to-nexus\/sdk/g' pnpm-lock.yaml
          sed -i 's/@cross-connect\/universal-provider/@to-nexus\/universal-provider/g' pnpm-lock.yaml
          sed -i 's/@cross-connect\/core/@to-nexus\/core/g' pnpm-lock.yaml
          sed -i 's/@cross-connect\/sign-client/@to-nexus\/sign-client/g' pnpm-lock.yaml
      - name: Install dependencies
        run: |
          pnpm config set @to-nexus:registry https://npm.pkg.github.com/
          pnpm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: pnpm run build
      - name: Publish package on GitHub Packages
        run: pnpm run publish:latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}